"""initial schema

Revision ID: 621130118ab9
Revises: 
Create Date: 2026-09-19 20:50:54.623974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621130118ab9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('common_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('Valid', 'Deleted', name='statusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('create_by', sa.String(length=64), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.Column('update_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_species_status'), ['status'], unique=False)

    op.create_table('user',
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('mobile', sa.String(length=64), nullable=True),
    sa.Column('login_password_hash', sa.String(length=512), nullable=False),
    sa.Column('login_password_level', sa.Enum('Low', 'Middle', 'High', name='passwordlevelenum'), nullable=False),
    sa.Column('login_password_update_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Valid', 'Deleted', 'Frozen', name='statusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('create_by', sa.String(length=64), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.Column('update_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_status'), ['status'], unique=False)

    op.create_table('file',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bucket', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('provider', sa.Enum('Minio', name='providerenum'), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('acl', sa.Enum('PRIVATE', 'PUBLIC_READ', name='aclenum'), nullable=False),
    sa.Column('status', sa.Enum('Valid', 'Invalid', name='statusenum'), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('create_by', sa.String(length=64), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.Column('update_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_status'), ['status'], unique=False)

    op.create_table('breed_image',
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('external_url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('Valid', 'Deleted', name='statusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('create_by', sa.String(length=64), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.Column('update_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breed_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breed_image_status'), ['status'], unique=False)

    op.create_table('breed',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('life_span', sa.String(length=32), nullable=True),
    sa.Column('temperament', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=128), nullable=True),
    sa.Column('country_codes', sa.String(length=32), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('bred_for', sa.String(length=512), nullable=True),
    sa.Column('perfect_for', sa.String(length=512), nullable=True),
    sa.Column('breed_group', sa.String(length=64), nullable=True),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('reference_image_id', sa.String(length=64), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('weight_imperial', sa.String(length=64), nullable=True),
    sa.Column('weight_metric', sa.String(length=64), nullable=True),
    sa.Column('height_imperial', sa.String(length=64), nullable=True),
    sa.Column('height_metric', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('Valid', 'Deleted', name='statusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('create_by', sa.String(length=64), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.Column('update_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['breed_image.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breed', schema=None) as batch_op:
        batch_op.create_index('breed_country_name_idx', ['country_code', 'name'], unique=False)
        batch_op.create_index('breed_species_group_idx', ['species_id', 'breed_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_breed_breed_group'), ['breed_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_breed_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_breed_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_breed_species_id'), ['species_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breed_status'), ['status'], unique=False)

    op.create_table('dog_image',
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('external_url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('Valid', 'Deleted', name='statusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('create_by', sa.String(length=64), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.Column('update_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dog_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dog_image_breed_id'), ['breed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dog_image_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dog_image_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dog_image_user_id'))
        batch_op.drop_index(batch_op.f('ix_dog_image_status'))
        batch_op.drop_index(batch_op.f('ix_dog_image_breed_id'))

    op.drop_table('dog_image')
    with op.batch_alter_table('breed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breed_status'))
        batch_op.drop_index(batch_op.f('ix_breed_species_id'))
        batch_op.drop_index(batch_op.f('ix_breed_name'))
        batch_op.drop_index(batch_op.f('ix_breed_country_code'))
        batch_op.drop_index(batch_op.f('ix_breed_breed_group'))
        batch_op.drop_index('breed_species_group_idx')
        batch_op.drop_index('breed_country_name_idx')

    op.drop_table('breed')
    with op.batch_alter_table('breed_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breed_image_status'))

    op.drop_table('breed_image')
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_status'))

    op.drop_table('file')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_status'))

    op.drop_table('user')
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_species_status'))

    op.drop_table('species')
    # ### end Alembic commands ###
